{% set name = "pygtail" %}
{% set version = "0.12.0" %}
{% set sha = "2acf2089f808cd0c3a23ad1b50059d46ee957f773a05080559a6451495437f2e" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - pygtail -h
  imports:
    - pygtail

about:
  home: https://github.com/bgreenlee/pygtail
  license: GPL-2
  license_family: GPL
  license_file: LICENSE
  summary: A python 'port' of logcheck’s logtail2

extra:
  recipe-maintainers:
    - tsenapathi
    - ChrisBarker-NOAA
