{% set name = "pygtail" %}
{% set version = "0.11.1" %}
{% set sha = "3af0825e7a5bb30af1798ed0a3d14f9a1cd7aa21b0e3f4430780f3ee3a09f3d7" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha: {{ sha }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - pygtail -h

about:
    home: https://github.com/bgreenlee/pygtail
    license: GPL-2
    license_family: GPL
    license_file: LICENSE
    summary: A python 'port' of logcheck’s logtail2

extra:
    recipe-maintainers:
        - tsenapathi
