{% set name = "pygtail" %}
{% set version = "0.14.0" %}
{% set sha = "55616d31a081eaaeb069d0946f2bc7e530ebf505d4c3c050f8e941786a3449d3" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - pygtail -h
  imports:
    - pygtail

about:
  home: https://github.com/bgreenlee/pygtail
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A python 'port' of logcheck’s logtail2

extra:
  recipe-maintainers:
    - tsenapathi
    - ChrisBarker-NOAA
