travis:
  secure:
    BINSTAR_TOKEN: yyDg2zDS4/7F6VFygV4gEw1MgsUwx5EA5Ue6pt1sjM8SpCUnA4tSjxDWsEj/JhppnLx67bJgnhFnttO1VR4XHhPiYkTko3LOZYKZMhVuO0Fnjyyr3+jQBTKRYvT0I92yn06u9ULiwEjzbbi4IlJ7tEY/5RXrZojruXI9cNV9PvhxRx0WlU3WTTIAgGaudJwIn7eBk6VPbnWrJn2TI7Gt9NS1CI19BY6n4SQ3b520UD6Za0pS677BbwgputxGiKpdNluqqR3zc0X/8fEYcOhjYgdAjRatUG6H8o9GdW2hVl4Ie2kHNqVI1H3TnAFTppAtuHWWARLQ5TfRVB0FYpia4dyHIpMlaKbFMDA/z6pN3aL8ZVQk3kSzhNFTCL46r4SihaKyWhqIjgIk82rlXoWbaFCJaTE0q5GuvhB+NUtUa183Ng44Ac8dOUZPd77GEc8O42/Wv43GzQyBKIBxslpiJUtG8EgCzP0GiG6MA+L0hrDkxojKBCGpHbeWWF1LTiVqQLP2XBEvnJtSJggzK8oPdkoHBvRyQ9B0KTqz+PlWBCBl4fvCIp64tZ8v/DumCIY98350OAgilSJ4j9zDVC+j2Ye8xeETerWdGcufFBkV3GgG+HOtvNC7ch45F24R1ps2ZtT0N8qkymfbvkYo2IddnnTn1/sD5TNxebPHjXgEpnc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
